/**
 * Web
 * No description provided (generated by Swagger Codegen https:
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https:
 * Do not edit the class manually.
 */

export interface AddProjectParticipantDto {
  projektId?: string;
  userId?: string;
}
